import Head from 'next/head'
import Link from 'next/link'
import { motion } from 'framer-motion'
import { HomeWrapper } from '../components/home/home.style'
import { HistorySection, Li, A } from '../components/home/history/style'
import { HeroSection } from '../components/home/hero/hero'
import { FooterSection } from '../components/home/footer/footer'
import { historyData } from '../data/historyData'
import { FadeTransition } from '../components/animations/pageTransitions/fadeTransition'
import { FadeInTransition } from '../components/animations/pageTransitions/toModels'
import HomePageTransition from '../components/animations/pageTransitions/homepageTransition'

export default function Home() {

  return (
    <>

      <Head>
        <title>Some stuff</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePageTransition>
        <HomeWrapper>
          <HeroSection />
          <HistorySection>
            <ul style={{ background: "#d1b18f" }}>
              {historyData.map((item, index) =>
                <Li key={item.id}>
                  <Link
                    href={{
                      pathname: '/history/[id]',
                      query: { id: item.id }
                    }}
                    passHref

                  >
                    <A>
                      {item.title}
                    </A>
                  </Link>
                </Li>
              )}
            </ul>
          </HistorySection>
          <FooterSection />
        </HomeWrapper>
      </HomePageTransition>
    </>
  )
}
